### ISSUE TITLE
DARMA is not installing

### ISSUE THREAD

**Issue by amsce-iscteiul** [jmgirard/DARMA#11]
When installing DARMA's latest version with the MCR 9.6 (R2019a) also installed on the computer it shows an error saying: "Error finding the installer class, an exception occurred while looking for class"

**Comment by jmgirard** [comment]
Hmm... I just installed it without any issues. Can you please do the following?
1. Please uninstall any old DARMA and MCR versions
2. Reinstall DARMA and let it install MCR automatically
3. If this still fails, try it on another computer account on this machine
4. If this still fails, try it on another computer
5. Let me know what the details are for your machine
