### ISSUE TITLE
Cannot select any menu options with new install

### ISSUE THREAD

**Issue by wilsj** [jmgirard/DARMA#12]
Hello, we just installed DARMA along with the MRC that matches our Matlab version (R2020a, v. 9.8) and cannot select any of the options in the dropdown menus (including opening a media file). Do you have any recommendations? Is it problematic to use the most recent version of the MRC?
Thanks!!

**Comment by jmgirard** [comment]
This is a little confusing, but you need to install the MCR version that matches the version of MATLAB that I compiled it with - not the version of MATLAB that you have. For the most recent version of DARMA, that is MCR 9.6 (R2019a). 

Another option is that, if you have a MATLAB license, you could download the source files and just run fig_launcher (without even needing MCR installed).

**Comment by wilsj** [comment]
Thanks for the quick feedback! I installed MCR 9.6 but still cannot select any menu options with the Collection window. This includes even the X to close the window (have to force close via the task manager). On the other hand, the Review window seems to be working well.

**Comment by jmgirard** [comment]
Can you run fig_launcher in MATLAB (not MCR)? This will likely return an error and seeing that would help a lot with troubleshooting.

**Comment by wilsj** [comment]
I ran fig_launcher in MATLAB, which did successfully bring up the first window. The same issue arose with the Collection window when I tried to open a video, and below is the resulting error. I'm happy to share it in another form if more useful.

>> fig_launcher
Warning: Name is nonexistent or not a directory: C:\Users\SHARE\Documents\MATLAB\Functions 
> In path (line 109)
  In addpath (line 86)
  In fig_launcher (line 48) 
Warning: ACTXCONTROLLIST will be removed in a future release. For more information see UI
Alternatives for MATLAB Apps on mathworks.com. 
> In actxcontrollist (line 21)
  In fig_launcher (line 50) 
Warning: The JavaFrame figure property will be removed in a future release. For more
information see UI Alternatives for MATLAB Apps on mathworks.com. 
> In fig_collect (line 72) 
Unrecognized function or variable 'findjobj'.

Error in fig_collect (line 98)
    jscrollpane = findjobj(handles.table_info);
 
Error while evaluating UIControl Callback.

Dot indexing is not supported for variables of this type.

Error in fig_collect>program_reset (line 898)
    handles = guidata(handles.figure_collect);

Error in fig_collect>menu_openmedia_Callback (line 162)
    program_reset(handles);
 
Error while evaluating Menu Callback.

Dot indexing is not supported for variables of this type.

Error in fig_collect>figure_collect_CloseReq (line 920)
    if handles.vlc.input.state==3,handles.vlc.playlist.togglePause(); end
 
Error while evaluating Figure CloseRequestFcn.

>>

**Comment by jmgirard** [comment]
I think there may be several issues here. First, can you confirm that you downloaded and unzipped all source files including the Functions folder (and not just fig_launcher.m)?

**Comment by wilsj** [comment]
Thanks for checking in. We did unzip the folder and left all of the other files in the folder as-is.

**Comment by wilsj** [comment]
Our desktop support person tried several troubleshooting strategies, none of which worked. We took screenshots of the collection and review windows, attached here. I’ve also attached the Event Viewer that documents the program ‘hanging.’ It was not very informative for us, but perhaps it will be more meaningful to you.

**Comment by jmgirard** [comment]
Sorry for my delay. Things are kind of crazy right now. Your attachments didn't post correctly to Github. Can you try again either on this website or send them directly to my email?
