### ISSUE TITLE
DARMA: Collect Ratings does not work

### ISSUE THREAD

**Issue by alecmartin0** [jmgirard/DARMA#14]
I just installed DARMA 6.09 running Windows 11. When I click Collect Ratings, the screen appears, but I cannot select anything (example: I cannot click 'settings' to 'set axis labels'. However, when I click Review Ratings, I am able to interact with the interface. Any ideas what could be happening? Thanks.

**Comment by jmgirard** [comment]
Do you have a USB joystick plugged in and detected? That is one of the main differences between Collect and Review.

**Comment by alecmartin0** [comment]
> Do you have a USB joystick plugged in and detected? That is one of the main differences between Collect and Review.

Issue has been resolved. The media player downloaded was the wrong type. Thanks
