### ISSUE TITLE
Audio alone

### ISSUE THREAD

**Issue by jesinj** [jmgirard/DARMA#3]
Hi, 

is it possible to annotate files with just audio alone (no video data)?

**Comment by jmgirard** [comment]
Sure can. Any media file that can be played in VLC media player can be rated in DARMA. Just load in the audio file directly or, if you want to control what raters see while listening, create a basic video file from an image series and add the audio file as an audio track. Let me know if you run into further issues or questions.

**Comment by jesinj** [comment]
Hi,

So  I installed DARMA, and I already have Matlab and VLC in my system. So once I run it, the DARMA window just opens, and when I click on any option, I just can hear an error sound. But there is no indication on what the error is. And then I cannot even close the window. Am I missing something?

**Comment by jmgirard** [comment]
Can you confirm that you installed the Matlab Runtime Compiler (MCR) during the DARMA installation and that your VLC installation is the 64-bit version with the ActiveX plugin installed?
