### ISSUE TITLE
could not detect a USB joystick

### ISSUE THREAD

**Issue by heng0122** [jmgirard/DARMA#4]
Hi, 
I have installed DARMA and VLC 64bit, but I face an error "DARMA could not detect a USB joystick. Please plug in a USB joystick and try again" after I click "Collect Ratings".
Could you please kindly advise? Thank you!
Regards,
Gladys

**Comment by jmgirard** [comment]
Hi Gladys, do you have a USB joystick plugged into your computer? Is it recognized by Windows?

**Comment by heng0122** [comment]
Hi Jeffrey,


Thanks for the reply and apologies for the belated response.


Sorry, I did not have a USB joystick plugged in previously. I'm looking into that now.


I understand that full-sized joysticks are recommended due to their greater precision of control. However, may I enquire if it is possible to run the program with a computer mouse instead? Thanks.


Regards,

Gladys

________________________________

**Comment by jmgirard** [comment]
It is only possible to use DARMA with a joystick, but you can use CARMA with a computer mouse to collect unidimensional ratings. <http://carma.jmgirard.com>
