### ISSUE TITLE
DARMA on Windows 10

### ISSUE THREAD

**Issue by heng0122** [jmgirard/DARMA#5]
Hi Jeffrey,

May I enquire if DARMA runs on any 64-bit computer, or it is more suitable for a particular Windows system? 

I downloaded it on Windows 10 and could get it started. However, the program tends to hang (in the sense that the joystick and ratings stop moving) but the audio continues playing.

I also downloaded it on Windows 7 and it works just fine. 

Please kindly advise. Thanks a lot!

**Comment by jmgirard** [comment]
It should work on any 64-bit Windows computer, including those running Windows 10. I'd recommend making sure the Windows 10 computer has enough RAM and has updated drivers installed.
