### ISSUE TITLE
Annotation file just stops - lines missing

### ISSUE THREAD

**Issue by lstappen** [jmgirard/DARMA#9]
Hi,
we received repeatedly annotation files (.csv) from various annotators where the length of the annotation file does not match the length of the video. Mostly it just stops after some time. For example, a video of 233 sec length with a bin size of 0.25 I would expect ~ 932 lines but the file just stops after 645 lines:
```
644: 159.75,-7.8,-335.4,0
645: 160,-7.8,-335.4,0
```
The rest of the file is missing. From the 2nd header line I can see that the correct video was annotated and also bin size looks fine.

I would estimate that every 25-30th file has that issue and is not mergeable to the other annotations of the same file. After reanotating the same file (or from other annotators) the annotation file is as expected. 

This happens throughout various annotators (therefore different machines) and video files. I am not able to detect a pattern behind that behaviour. Any ideas? Happy to help with debugging if I would know where to start...

Best,
Lukas

**Comment by jmgirard** [comment]
Hi Lukas,

Sorry to hear about this issue. I've not come across it before. Do you happen to have access to MATLAB? Running DARMA from the source code in MATLAB rather than from the compiled executable might reveal more information if the cause is a MATLAB-based error. However, it is strange that it would continue playing the video and then export a partial annotation file if there were a MATLAB-based error... But this would be one place to start if possible. 

In the meantime, I would also recommend you do the "usual" DARMA troubleshooting steps if you haven't already (e.g., updating all your drivers and making sure the video file is on the local storage device and not on a USB or network drive). 

**Edit:** Running in MATLAB would also allow you to see the joystick samples data, which gets dumped to the console right before binning. If there are samples displayed after the cutoff point (e.g., second 160 in your example above), then we know it is an issue with the binning.
https://github.com/jmgirard/DARMA/blob/9d1ca022bbcef745276259890b42ad1722b87aef/fig_collect.m#L773

**Comment by jmgirard** [comment]
Also, this doesn't fit the idea that the same file would sometimes work and sometimes fail on the same computer at different times, but one problem that occurred to me that might cause the behavior you're describing would be if VLC was not reading the video file's duration properly:
https://github.com/jmgirard/DARMA/blob/9d1ca022bbcef745276259890b42ad1722b87aef/fig_collect.m#L182

This wrong duration would then be used to set the anchors for the binning of joystick samples:
https://github.com/jmgirard/DARMA/blob/9d1ca022bbcef745276259890b42ad1722b87aef/fig_collect.m#L774-L784

That would mean that all the samples were collected properly (hence the absence of a crash, freeze, or error message/beep) but they were not binned properly. Perhaps I can compare the video duration from VLC to the number of samples and spit out an error if they are grossly different.

**Comment by lstappen** [comment]
Hi!
Thank you for the quick response and your answers! 

> However, it is strange that it would continue playing the video and then export a partial annotation file if there were a MATLAB-based error...

Exactly, all of them were able to annotate the entire file (without any errors) and store the file (which is only possible after the end of the video). 

> In the meantime, I would also recommend you do the "usual" DARMA troubleshooting steps if you haven't already (e.g., updating all your drivers and making sure the video file is on the local storage device and not on a USB or network drive).

All videos are copied from an NAS and then stored and annotated from the local HD. We also followed the troubleshooting routines and updated the drivers. In the beginning, I thought it might be RAM dependent (since problems with VM are reported) but also annotators with cutting-edge machines (e.g. dell xps 13 9370) have the issue.

> Edit: Running in MATLAB would also allow you to see the joystick samples data, which gets dumped to the console right before binning. If there are samples displayed after the cutoff point (e.g., second 160 in your example above), then we know it is an issue with the binning.

I am going to ask the uni department if we have a MATLAB licence. Is it possible to activate a debug mode with these dumps? Otherwise, I am going to write a debug function/log with this dump (as soon I find time) and then distribute a compiled version to the annotators. I think that might be the fastest way to narrow it down, since it only happens rarely, it might be hard to replicate the issue otherwise.

> Also, this doesn't fit the idea that the same file would sometimes work and sometimes fail on the same computer at different times, but one problem that occurred to me that might cause the behavior you're describing would be if VLC was not reading the video file's duration properly:

Sounds also reasonable and I am going to add this the the dump function.

-----

I attached a few faulty exports from 3 annotators (1,3,4): [error_files.zip](https://github.com/jmgirard/DARMA/files/3314924/error_files.zip)

The naming convention is VideoID_ID_Duration_[Annotation_Type]_[Personal_Annotator_ID].csv. The expected number of lines can be calculated by taking the _Duration_ * 4 (0.25ms). We are only using the Y-axis (e.g. V = Valence,  A = Arousal) for annotation and 720p videos in .mp4 format. 

1. VideoID = 150: One faulty, one correct file from the same annotator.
 _ERROR.csv: "clean" cut off after 645 lines
 _NOERROR.csv: re-annotated file one day later from the same annotator & machine (4) 

2. VideoIDs 19 & 111:
 I just saw that there are also errors that look different than the others mentioned above. The timestamp is still printed but then it stops. 
 
19: 
> 58.25,-7.8,250,0
58.5,-7.8,250,0
58.75

111:
> 339.5,-7.8,7.8,0
339.75,-7.8,7.8,0
340

 Best,
Lukas

**Comment by jmgirard** [comment]
We could make a special version of the program that always writes the joystick samples to a text file before binning. Then you would just need to wait until you notice an error in the output and then go find the corresponding text file.

----

> We are only using the Y-axis (e.g. V = Valence, A = Arousal) for annotation and 720p videos in .mp4 format.

If you are only using the Y-axis, would CARMA be a better match than DARMA? Or am I misunderstanding what you meant?
http://carma.jmgirard.com/

**Comment by lstappen** [comment]
Yes that would be great! As soon I figure out if we have a MATLAB licence I can start with that :)

> If you are only using the Y-axis, would CARMA be a better match than DARMA? Or am I misunderstanding what you meant?
http://carma.jmgirard.com/

To be honest, we were not aware of CARMA. Besides Y we use also using the binary/continuous annotation (button 1) - if this is also supported, it definitely would have been the better fit...next time!

**Comment by jmgirard** [comment]
CARMA doesn't current log the joystick button, but it would be pretty trivial to add that functionality if it is important to you.

**Comment by lstappen** [comment]
Hi!
Unfortunately there are no free MATLAB licences available at our university... Only idea I have is I fork it, do some blind coding and you compile it?
Best,
Lukas

**Comment by jmgirard** [comment]
That works for me!

P.S. This is one of the main reasons I no longer use MATLAB. It sucks to have open source software that people can't use.

**Comment by lstappen** [comment]
Great!

Also we good a new error today. All resulting files look like this:

`Time of Rating,25-Jun-2019 10:28:48,,
Multimedia File,197_ZtrxxGmqU1c_167.mp4,,
Magnitude,1000,,
Second,Valence,Arousal,Button
%%%%%%,%%%%%%,%%%%%%,%%%%%%
0.25,-7.8,7.8,0
0.5,NaN,NaN,NaN
0.75,-7.8,7.8,0
1,-7.8,7.8,0
1.25,NaN,NaN,NaN
1.5,NaN,NaN,NaN
1.75,-7.8,7.8,0
2,NaN,NaN,NaN`
...

so every 2-3 lines are NaN. Worked before without any problems... We uninstalled DARMA & Matlab exec., deleted all temporary files and reinstalled it - same problem. Also we did a fall back to 6.02 instead of .03 - same result. Import for review gives the error message:

`"Annotation file must have the same bin size as the other annotation files."`

There is no other annotation file imported. Any idea what this might be caused by?

Thank you

**Comment by jmgirard** [comment]
Did anything chance on the machines to trigger this new error?

I'll recompile DARMA with the newest version of MATLAB and let's see if that makes any difference. Maybe there are bugs in the old version of the MATLAB compiler runtime.

**Comment by jmgirard** [comment]
Ok, check out v6.04, which uses the newest version of MATLAB and adds some new features. The ability to create log files and the addition of video duration to the output file should be helpful in troubleshooting your issues: https://github.com/jmgirard/DARMA/releases/tag/v6.04

**Comment by lstappen** [comment]
Thanks a lot for the super quick response! Going to check this out today and give feedback :)

> Did anything chance on the machines to trigger this new error?
> I'll recompile DARMA with the newest version of MATLAB and let's see if that makes any difference. Maybe there are bugs in the old version of the MATLAB compiler runtime.

This is definitely possible. I tried to avoid this by using the machine for annotation only. I am also not aware that there were any win updates since.

**Comment by lstappen** [comment]
Hi,
sorry that it took so long. We first removed 6.03 and the corresponding runtime, all temp and installation folders manually and installed 6.04 + new runtime. In 6.04 the video and the annotation area disappeared as you can see in the screenshot. Starting it from cmd does not show any matlab errors...
![Screenshot_DARMA 6 04](https://user-images.githubusercontent.com/24368716/60358931-de69ba00-99d7-11e9-8b94-082a69f95a75.png)

I am also not able to close it or change any setting (e.g. activate debug). There is the windows sound ringing as if there would be another windows open that first have to be interacted with before you allow to do something else - but I cannot see this window (also not in the task manager) - there are only 2 the entry window where you can choose between collect and review and the actual collect window. Any idea what this can caused by?

To be sure, we reinstalled windows (also the reason why it took a little longer). Unfortunately, I still have the same issue (also I double checked that all drivers, vlc etc. is reinstalled). Then, I installed 6.03 again on the plain machine and it is working. I am going to install 6.04 on another computer tonight and see if this window area problem is replicable.  

I installed the two Darma & Matlab version in different folders now - so I am able to run both in parallel (hopefully) without causing any problems to the other version. If you have an idea how to fix this issue on 6.04 let me know - very happy to help finding a long-term solution and try the debug function because I don't know how long 6.03 holds before we have to reinstall the entire machine again :)

**Comment by jmgirard** [comment]
I think this is a bug with the window resizing function. Let me look into it.

**Comment by jmgirard** [comment]
Ok, I found a bug in the window resizing function and fixed it (https://github.com/jmgirard/DARMA/commit/ea749fc9a4ed2756eec4df4296494e1c2e0207db). Please try version 6.05:

https://github.com/jmgirard/DARMA/releases/tag/v6.05

**Comment by lstappen** [comment]
Great! It shows up now. Going to roll this version out for the annotators where the probs with the bin size occurs and hope that I can give feedback soon.
Thank you

**Comment by jmgirard** [comment]
Hopefully no news is good news. Let me know if things seem resolved and I will apply the same changes to CARMA.
